name: Upload Go test results

permissions:
  contents: read

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

env:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Install dependencies
        run: go get .

      - name: Check Test Coverage
        run: |
          go test -coverprofile=coverage.out
